version: "3.7"

services:
  bulkit-demo:
    image: digisquad/cssninja.bulkit-demo:latest
    networks:
      - cssninja-services
    restart: "${DEMO_RESTART:-unless-stopped}"
    labels:
      traefik.enable: true
      traefik.docker.network: "cssninja-services"
      traefik.http.routers.bulkit-demo.entrypoints: "http"
      traefik.http.routers.bulkit-demo.rule: "Host(`bulkit.${HOST:-127.0.0.1.nip.io}`)"
      traefik.http.routers.bulkit-demo.middlewares: "https-redirect@file"
      traefik.http.services.bulkit-demo-https.loadbalancer.server.port: 8080
      traefik.http.routers.bulkit-demo-https.rule: "Host(`bulkit.${HOST:-127.0.0.1.nip.io}`)"
      traefik.http.routers.bulkit-demo-https.tls: true
      traefik.http.routers.bulkit-demo-https.entrypoints: "https"
      traefik.http.routers.bulkit-demo-https.tls.certresolver: "http"

networks:
  cssninja-services:
    external: true
